### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by yeupou** [the-djmaze/snappymail#419] opened 2022-05-26 14:46 UTC
With some hard clients like Mozilla Thunderbird and some web clients like Roundcube, it is possible to tag messages consistently 
(Important/Work/Personal). So I assume these tags are passed through IMAP.

Would you consider implement such tags support in Snappymail?

(I'd like to thank you once again for the great work being done on Snappymail. Really a cool piece of software).

Regards,

**Comment by the-djmaze** [comment] 2022-05-26 16:36
I'm sorry to say, but it's not part of IMAP standards.
Only "flags" are defined and that is not the same as tags.

However, the solution is to use a local storage to store tags with uid of message in the folder.

Moving a message generates a new uid so needs tagging again.

Thunderbird and RoundCube use databases to manage these and the problem is that you can't share tags between these programs easily.

So, the solution is to modify the message and add/edit `x-` headers to manage these.

**Comment by yeupou** [comment] 2022-05-28 09:54
Hi,

It is odd, with my company setup (no clue exactly how it is set up), we have both Thunderbird and Roundcube, and the tags shows in both clients:

- they do not use flags for this (flags are also used, but same as Snappymail, no issue with flags).
- It do not see anything in the mails headers regarding these.


Maybe it uses this:
https://github.com/mike-kfed/roundcube-thunderbird_labels
https://sourceforge.net/projects/tagspluginrc/
("_will follow the same semantic as Thunderbird to manage tag, so tags set using this plugins will be seen in Thunderbird and vice-versa_")

**Comment by the-djmaze** [comment] 2022-05-28 22:10
Found it!
When the IMAP server supports "*" flags, the Thunderbird "labels" are stored as flags.
These are marked as `$label1` or `$Label1` (no idea which is correct).
There are a few hard-coded:
```
0 – Remove all tags
1 – Important
2 – Work
3 – Personal
4 – To Do
5 – Later
```

To know if this is correct, and works in SnappyMail:
1. open browser debug network tab
2. open a message that should have "labels"
3. click on the request in the network tab and check the result

The labels should be in the Flags part
![afbeelding](https://user-images.githubusercontent.com/3752035/170844324-825b9cab-0ada-4545-a326-ea2a4b1d037e.png)

**Comment by yeupou** [comment] 2022-05-29 08:34
I did a test setting "Work" in Thunderbird

I get:

Flags | [ "\\seen", "$label2" ]
  0 | "\\seen" 
  1 | "$label2"

(But soon enough it disappears. I wonder if it is not Snappymail that actually remove the extra flag. Because if I do not manipulate the messages with Snappymail, it seem to stay. But it might be offlineimap sync between servers)

**Comment by the-djmaze** [comment] 2022-05-29 19:18
> ahem, confirmed as probably caused by offlineimap

You could try https://imapsync.lamiral.info/ instead.
I use that to migrate accounts.

**Comment by the-djmaze** [comment] 2022-05-30 06:45
I've installed Thunderbird to make an additional test with custom tags.
As it seems you can:
![afbeelding](https://user-images.githubusercontent.com/3752035/170932722-5a011409-83c2-4c19-9a4a-f0828a9b0f88.png)

The result is not `$label##` but just the name:
```
IMAP[DATA]: > TAG3 SELECT "INBOX"\r\n
IMAP[DATA]: < * FLAGS (\Answered \Flagged \Deleted \Seen \Draft $FORWARDED $SENT $SIGNED $TODO $ERROR $QUEUED $label1 $label5 test)\r\n
IMAP[DATA]: < * OK [PERMANENTFLAGS (\Answered \Flagged \Deleted \Seen \Draft $FORWARDED $SENT $SIGNED $TODO $ERROR $QUEUED $label1 $label5 test \*)] Flags permitted.\r\n
IMAP[DATA]: < * 542 FETCH (... FLAGS (\Seen $label1 $label5 test) ...)

```

**Comment by yeupou** [comment] 2022-05-30 17:18
Unfortunately imapsync is not doing two-way sync https://imapsync.lamiral.info/FAQ.d/FAQ.Two_Ways_Sync.txt and suggest to use imapoffline or mbsync.

(and I already tried mbsync and got mad with it cf end of https://yeupou.wordpress.com/2014/02/10/replicating-imaps-dovecot-mails-folders-and-sharing-through-owncloud-contacts-kmail-roundcube-etc/  )

**Comment by yeupou** [comment] 2022-05-31 22:04
Ok, I found out that interimap seems to be a good alternative, even more efficient.
https://guilhem.org/interimap/

and work out of the box with dovecot.

config is as simple as 

$ mkdir -p ~/.config/interimap ~/.local/share
$ cat ~/.config/interimap/config 
[local]
type=tunnel
command=exec /usr/lib/dovecot/imap

[remote]
type=tunnel
command=ssh -q OTHERSERVER -p PORT '/usr/lib/dovecot/imap'


![Screenshot 2022-06-01 at Boîte mail - e2](https://user-images.githubusercontent.com/1160681/171291629-69a4e226-feb0-4859-8399-d6c75985fd25.png)

Seems to be working fine!
However it is not clear to me how to set the custom flag within Snappymail (not yet implemented maybe!)

Anyway, that's great, plus it gave me opportunity to switch to intermap that seems promising.

**Comment by the-djmaze** [comment] 2022-06-01 21:32
> However it is not clear to me how to set the custom flag within Snappymail (not yet implemented maybe!)

Correct, i was only playing with colors and testing custom (unicode/utf-8) tags.
And also added the Thunderbird mode:
https://github.com/the-djmaze/snappymail/blob/a43fadb4e8ffa424b06159346154823335f912a0/dev/Styles/User/MessageList.less#L459-L476

There are so many ways to make it visible (with problems).

For example in Thunderbird you have a message with two keywords (tags), then only 1 color is shown (the other not).
Same idea with my confusing colored checkbox (some people think "why a colored checkbox?!?")

A solution might be to define a color per keyword and then make a `linear-gradient()` of them and make the list very colorful...
Oh right, colors defeats all purpose for color blinds...

So yes, i am playing but nothing concrete yet.

**Comment by yeupou** [comment] 2022-06-02 13:05
Testing thunderbird, as I did a few test:
- 1 - important always take over
-  if you had more flags in increasing order (2, 3, 4 ), it keep the first one
-  if you go in decreasing order (5, 4, 3), it actually change over to the newly selected

So Thunderbird use some sort of priority. If there are more than one tag, it should be the most important (except when it's not... sometimes if you toy with flags, it fails to do so).

The linear-gradient is interesting but can easily get confusing (especially if we extend to custom colors per user choice). I think Thunderbird approach is reasonable:   shows by priority and list all tags in the message window

![image](https://user-images.githubusercontent.com/1160681/171635482-b8afd123-2296-4df9-8ecb-75e57b50f8dc.png)


Note that Roundcube seems to do the contrary (priority to higher number), which makes sense to give priority to user custom flags but is odd since since "important" get lowest priority.

**Comment by the-djmaze** [comment] 2022-06-02 19:28
Ok, now it is like thunderbird.
I've made a seperate .less file and added the info to the MessageView:
![afbeelding](https://user-images.githubusercontent.com/3752035/171722586-c413e7dd-5958-4390-89d2-e1698afb8a25.png)

**Comment by the-djmaze** [comment] 2022-06-03 11:50
I've also implemented tag toggle.
Could you try this test release and provide feedback if you like it?

[snappymail-2.16.3.1.tar.gz](https://github.com/the-djmaze/snappymail/files/8832071/snappymail-2.16.3.1.tar.gz)
[snappymail-2.16.3.1.zip](https://github.com/the-djmaze/snappymail/files/8832072/snappymail-2.16.3.1.zip)

**Comment by yeupou** [comment] 2022-06-03 17:26
Is there a .deb for this release so I can easily test it?

**Comment by the-djmaze** [comment] 2022-06-06 12:16
No, but i can create one

**Comment by the-djmaze** [comment] 2022-06-07 13:51
You can try it with this one:
https://snappymail.eu/repository/deb/snappymail_2.16.3.3-1_all.deb

**Comment by yeupou** [comment] 2022-06-09 17:13
Ok, that is very cool. Seems to work nicely.

Minor cosmetics:
 * french i18n: Work should be translated into Travail instead of Travailler 
 * 4 tags instead of 5, the "4 - To Do" in blue is missing
 * 2 extra flags showing up: $notjunk  $readreceipt

**Comment by yeupou** [comment] 2022-06-09 17:50
Actually "4 - To Do" is not missing.
On some other mail, using "4 - To Do" with thunderbird, then it is "3 - Personal" in green that is missing.

Also, french i18n "4 - To Do" is translated by "Faire". It should be "À faire" (To = À, Do = Faire)

**Comment by yeupou** [comment] 2022-06-10 20:07
I also noticed the following:

![image](https://user-images.githubusercontent.com/1160681/173142278-77c53505-c7b1-4e09-83d1-fe8974ced0aa.png)

The mail was wrongly flagged as spam so I unspammed it. 
It kept an extra junk tag.

The tag list seems to depend on the currently visible tags within a given mailbox.
For some folder, I get none :

![image](https://user-images.githubusercontent.com/1160681/173142606-7eb5fa99-5e50-4501-89c2-90020dcb74ef.png)

or else 

![image](https://user-images.githubusercontent.com/1160681/173142684-e46d21d3-6e96-4de6-9705-841fd3cd22ed.png)

**Comment by yeupou** [comment] 2022-06-10 20:13
If one is picky,  Etiquettes => Étiquettes  :-)  (sorry, the mistake was in my first post about it)

**Comment by yeupou** [comment] 2022-07-03 07:15
Note that I was toying with the option to activate or remove the checkboxes (in the message list) and it gave strange results: missing tag colors etc.

**Comment by mandusm** [comment] 2022-07-08 02:27
Woah, hang on. How do I enable this on my install? I can see the flags in the JSON object, but I do not see tags in the UI at all. I upgraded to 2.16.3.2 but still nothing. Is there a config option I have to set?

**Comment by yeupou** [comment] 2022-07-19 19:28
Testing latest release! Very cool.

**Comment by the-djmaze** [comment] 2022-10-05 09:36
I've just improved the Advanced Search window to allow searching for a specific keyword/tag/label
![afbeelding](https://user-images.githubusercontent.com/3752035/194029827-93d74a3e-f888-490d-84dd-c329b85ecc08.png)

**Closed** 2024-03-19 14:34 UTC
Labels: enhancement
