### ISSUE TITLE
Nextcloud 25.03/Snappymail 2.25--Call to undefined method RainLoop\Actions::ThemeLink() in file

### ISSUE THREAD

**Issue by danielmueller1958** [the-djmaze/snappymail#889] opened 2023-01-30 09:27 UTC
This  is about an error about Snyppymail updating from V 2.24.5 to 2.25. in Nextcloud 25.03
Expected behavior: After Update should be working as usual
But if I call snappymail in Nextcloud there is an internal Server Error:
![grafik](https://user-images.githubusercontent.com/46891458/215436827-71ef152b-9e94-4384-86eb-aaf17a17e09f.png)

And  there is following log enty:

[index] Fehler: Exception: Call to undefined method RainLoop\Actions::ThemeLink() in file '/var/www/nextcloud/apps/snappymail/lib/Controller/PageController.php' line 69 at <<closure>>

0. /var/www/nextcloud/lib/private/AppFramework/App.php line 172
   OC\AppFramework\Http\Dispatcher->dispatch()
1. /var/www/nextcloud/lib/private/Route/Router.php line 298
   OC\AppFramework\App::main()
2. /var/www/nextcloud/lib/base.php line 1047
   OC\Route\Router->match()
3. /var/www/nextcloud/index.php line 36
   OC::handleRequest()

GET /apps/snappymail/
from xxx.xxx.xxx.xxx by mueller at 2023-01-30T09:22:14+01:00
{"reqId":"6ecAXqae00TvJc7DgGGy","level":3,"time":"2023-01-30T09:22:14+01:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"mueller","app":"index","method":"GET","url":"/apps/snappymail/","message":"Call to undefined method RainLoop\\Actions::ThemeLink() in file '/var/www/nextcloud/apps/snappymail/lib/Controller/PageController.php' line 69","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0","version":"25.0.3.3","exception":{"Exception":"Exception","Message":"Call to undefined method RainLoop\\Actions::ThemeLink() in file '/var/www/nextcloud/apps/snappymail/lib/Controller/PageController.php' line 69","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1047,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","Line":165,"Previous":{"Exception":"Error","Message":"Call to undefined method RainLoop\\Actions::ThemeLink()","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":225,"function":"index","class":"OCA\\SnappyMail\\Controller\\PageController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":133,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1047,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/apps/snappymail/lib/Controller/PageController.php","Line":69},"CustomMessage":"--"},"id":"63d78ca02bcf7"}

**What I recognized is, the file PageController.php'  changed  from**:
 61                 $params = [
     62                         'Admin' => $bAdmin ? 1 : 0,
     63                         'LoadingDescriptionEsc' => \htmlspecialchars($oConfig->Get('webmail', 'loading_description', 'SnappyMail'), ENT_QUOTES|ENT_IGNORE, 'UTF-8'),
     64                         'BaseTemplates' => \RainLoop\Utils::ClearHtmlOutput($oServiceActions->compileTemplates($bAdmin)),
     65                         'BaseAppBootScript' => \file_get_contents(APP_VERSION_ROOT_PATH.'static/js'.($sAppJsMin ? '/min' : '').'/boot'.$sAppJsMin.'.js'),
     66                         'BaseAppBootScriptNonce' => $sNonce,
     67                         'BaseLanguage' => $oActions->compileLanguage($sLanguage, $bAdmin),
     68                         'BaseAppBootCss' => \file_get_contents(APP_VERSION_ROOT_PATH.'static/css/boot'.$sAppCssMin.'.css'),
     69                         'BaseAppThemeCssLink' => $oActions->ThemeLink($bAdmin),
     70                         'BaseAppThemeCss' => \preg_replace(
     71                                 '/\\s*([:;{},]+)\\s*/s',
     72                                 '$1',
     73                                 $oActions->compileCss($oActions->GetTheme($bAdmin), $bAdmin)
     74                         )
     75                 ];

**To**:
 61                 $params = [
     62                         'Admin' => $bAdmin ? 1 : 0,
     63                         'LoadingDescriptionEsc' => \htmlspecialchars($oConfig->Get('webmail', 'loading_description', 'SnappyMail'), ENT_QUOTES|ENT_IGNORE, 'UTF-8'),
     64                         'BaseTemplates' => \RainLoop\Utils::ClearHtmlOutput($oServiceActions->compileTemplates($bAdmin)),
     65                         'BaseAppBootScript' => \file_get_contents(APP_VERSION_ROOT_PATH.'static/js'.($sAppJsMin ? '/min' : '').'/boot'.$sAppJsMin.'.js'),
     66                         'BaseAppBootScriptNonce' => $sNonce,
     67                         'BaseLanguage' => $oActions->compileLanguage($sLanguage, $bAdmin),
     68                         'BaseAppBootCss' => \file_get_contents(APP_VERSION_ROOT_PATH.'static/css/boot'.$sAppCssMin.'.css'),
     69                         'BaseAppThemeCss' => \preg_replace(
     70                                 '/\\s*([:;{},]+)\\s*/s',
     71                                 '$1',
     72                                 $oActions->compileCss($oActions->GetTheme($bAdmin), $bAdmin)
     73                         )
     74                 ];

How ca I solve that issue?

**Comment by the-djmaze** [comment] 2023-01-30 09:57
Duplicate of #880

**Closed by the-djmaze** 2023-01-30 09:57 UTC

**Comment by the-djmaze** [comment] 2023-01-30 14:57
v2.25.1 will automatically reset your php opcache.
Try with update when available

**Comment by danielmueller1958** [comment] 2023-01-30 15:03
Thank you for your reply.

I did it meanwhile by, uninstall snappymail from nextcloud.

Then stopping my php81-fpm, then installed snappymail from cli, by occ app:install snappymail.

Turned on php-fpm again and this way did the trick.

 

 

Von: the-djmaze ***@***.*** 
Gesendet: Montag, 30. Januar 2023 15:58
An: the-djmaze/snappymail ***@***.***>
Cc: danielmueller1958 ***@***.***>; Author ***@***.***>
Betreff: Re: [the-djmaze/snappymail] Nextcloud 25.03/Snappymail 2.25--Call to undefined method RainLoop\Actions::ThemeLink() in file (Issue #889)

 

v2.25.1 will automatically reset your php opcache.
Try with update when available
