### ISSUE TITLE
always maintenance mode

### ISSUE THREAD

**Issue by caww** [the-djmaze/snappymail#1315] opened 2023-11-17 06:13 UTC
**Describe the bug**
Maintenance mode after upgrade to 2.29.2 and no way to switch to working mode. Nextcloud totally broken - not working.
No errors found - just always maintenance mode. Tried to do upgrade 5 times always same result.

Tried:
SSh commands occ maintenance:disabled 
change variable in config.php
but ALWAYS in maintenance mode 
I restored backup of DATABASE to previoud state before upgrade

**To Reproduce**
1. Use latest 2.29.1 version of snappymain and Nextcloud 27.1.3 + php 8.2 (nginx + php-fpm)
2. Click on upgrade in wb version or in ssh not important
3. Maintenance mode always enabled and no way to disable it

**Expected behavior**
working state restored after upgrade

**Please complete the following information:**
- Browser: any
- PHP version: 8.2
- SnappyMail Version: 2.29.1->2.29.2
- Mode: nextcloud

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
No logs found with errors

**Comment by the-djmaze** [comment] 2023-11-20 11:21
Duplicate of  #929

**Closed by the-djmaze** 2023-11-20 11:21 UTC
