### ISSUE TITLE
Shortcuts and Search Input

### ISSUE THREAD

**Issue by chrisrex** [the-djmaze/snappymail#270] opened 2022-03-06 10:48 UTC
Hi,
Keyboard shortcuts interfere with typing in the search box. For example: I can not type the letter "t", "z", "u" ...
Is it possible to disable the shortuts?
Best regards
Christoph

**Comment by terribleplan** [comment] 2022-03-07 04:11
Duplicate of #265

AFAICT there is no release (yet) incorporating the fix to that issue.

**Closed** 2022-03-07 12:36 UTC
Labels: bug, duplicate
