### ISSUE TITLE
[105] Missing snappymail/v/2.19.5/include.php

### ISSUE THREAD

**Issue by elhananjair** [the-djmaze/snappymail#606] opened 2022-11-01 08:32 UTC
**Describe the bug**
Every time I update snappymail I see this error: `[105] Missing snappymail/v/2.19.5/include.php` I fix it by deleting some directories from snappymail appdata. Do I always need to do this manually, or is there a way to fix it?

**To Reproduce**
1. Update snappymail and you see the error when you click on the snappymail app icon

**Expected behavior**
The updated app should start without any tweaks 

**Screenshots**

**Please complete the following information:**
- Browser: Firefox
- IMAP daemon: [e.g. courier, dovecot]
- PHP version: 8.0.24
- SnappyMail Version: 2.19.6

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
Place them here (few lines) or as attachments (many lines)

**Additional context**

**Comment by the-djmaze** [comment] 2022-11-01 09:08
Duplicate of #603

https://github.com/the-djmaze/snappymail/wiki/FAQ#105-missing-snappymailvxxxincludephp

**Closed by the-djmaze** 2022-11-01 09:08 UTC
