### ISSUE TITLE
Account name empty

### ISSUE THREAD

**Issue by mmallejac** [the-djmaze/snappymail#1188] opened 2023-06-21 15:52 UTC
Hello !

I've noticed a small issue, when having 2 or more accounts declared.
When adding an account, 3 fields are presents : email, pass and name.
If the account name is not filled, it can get tricky then to manage it

To avoid that, It would probably be good to set name equal email when name is empty.

Here with 3 accounts, first did not get a name:

![image](https://github.com/the-djmaze/snappymail/assets/11666281/f2920364-bbdf-4221-9b1a-3e124f9e2681)

In the account list:

![image](https://github.com/the-djmaze/snappymail/assets/11666281/970e3071-91df-45c7-91fd-10840682ad8d)

So then, how to delete it ?! 

Thanks in advance !
SnappyMail is really going greater and greater, a pleasure to work with !

Michel

**Comment by the-djmaze** [comment] 2023-06-22 10:22
Duplicate of #1180

**Closed by the-djmaze** 2023-06-22 10:22 UTC
Labels: duplicate
