### ISSUE TITLE
Reloading always switches to sign in page

### ISSUE THREAD

**Issue by yasuhirokimura** [the-djmaze/snappymail#803] opened 2022-12-28 05:52 UTC
# Steps to reproduce the issue

1. Access to the sign in page.
2. Enter username and password. Then click 'Sign In'.
   -> Mailer page is displayed
3. Click 'Reload' button of the web browser.

# Expected behavior

Mailer page is displayed again.

# What really happens

Sign in page is displayed.

# Conditions

- Browser: Google Chrome 108.0.5359.125 on 64bit Windows 2022H2
- IMAP daemon: Dovecot 2.3.20
- PHP version: 8.1.13
- SnappyMail Version: 2.24.2

**Comment by the-djmaze** [comment] 2022-12-28 09:07
Duplicate of #800

**Closed by the-djmaze** 2022-12-28 09:07 UTC
Labels: duplicate
