### ISSUE TITLE
Message body is empty: It's an error or more an information

### ISSUE THREAD

**Issue by Psychi1** [the-djmaze/snappymail#1073] opened 2023-04-05 05:13 UTC
**Describe the bug**

An empty message body is not an error, it's more an information. These error message also shows when adding an attachement without an text.

From the [RFC 5322: Internet Message Format, Section 2.1](https://www.rfc-editor.org/rfc/rfc5322#section-2.1)

>   A message consists of header fields (collectively called "the header
>   section of the message") followed, optionally, by a body

**Expected behavior**

It should be possible to save and send mails with empty message bodies. Especially if the most importent information already exits in the subject, e.g. "Contract" with an Attachment. There is no necessity for more information in the text part. 

Downgrade an empty message body from error to information.

**Please complete the following information:**
- SnappyMail Version: 2.72.2

**Comment by the-djmaze** [comment] 2023-04-06 21:53
Duplicate of #1052

**Closed** 2023-04-06 21:53 UTC
Labels: duplicate
