### ISSUE TITLE
Right click menu

### ISSUE THREAD

**Issue by leo852** [the-djmaze/snappymail#1423] opened 2024-02-05 21:36 UTC
It will be a lot more continent if users are able to right click on an email to delete/spam/forward the email

Maybe something similar to gmail or zoho mail?

**Comment by the-djmaze** [comment] 2024-02-05 21:50
Duplicate of #461

**Closed by the-djmaze** 2024-02-05 21:50 UTC

**Comment by leo852** [comment] 2024-02-05 21:54
> Duplicate of #461

Just saw that. You said you're not going to work on it cause it's not compatible to touch screen.. but I guess lots of mail users are using PC in the office. And for users using snappymail might be some small companies with needs of email client, so mostly office users?

**Comment by the-djmaze** [comment] 2024-02-05 22:15
You could write a plugin that does it?
