### ISSUE TITLE
Nextcloud Update SnappyMail 2.35.3 Login- An error occurred.

### ISSUE THREAD

**Issue by wo88888** [the-djmaze/snappymail#1493] opened 2024-03-14 07:48 UTC
Hello,

after Nextcloud Update SnappyMail 2.35.3 i get the following error when i go to Nextcloud App SnappyMail, SnappyMail don't start:

**_An error occurred.
Please refresh the page and try again.TypeError: (intermediate value).toLowerCase is not a function_**

When i save the login in additional settings the app starts without an error.

Thank you for your help!

W

**Comment by the-djmaze** [comment] 2024-03-15 00:42
Duplicate of #1491

**Closed** 2024-03-16 00:07 UTC
Labels: duplicate

**Comment by wo88888** [comment] 2024-03-18 05:53
Thank you very much to solute the problem.

Thank you for solving the problem.
What security do you use when I save the password in Nextcloud in additional settings?

**Comment by the-djmaze** [comment] 2024-03-18 08:43
Sodium, ooenssl or xxtea, depending on what your PHP supports.

**Comment by wo88888** [comment] 2024-03-18 10:24
How is the password stored in encrypted form?
Thank you!

**Comment by the-djmaze** [comment] 2024-03-18 11:31
`[type, iv/nonce/salt, Encrypt(json_encode(password), iv/nonce/salt, key)]`
