### ISSUE TITLE
v2.35.2 BUG Theme Nextcloud V25+ in dark mode

### ISSUE THREAD

**Issue by PeopleInside** [the-djmaze/snappymail#1487] opened 2024-03-10 23:13 UTC
**Describe the bug**

This issue was not present in snappymail v2.35.1 and it's present on snappymail v2.35.2
Using the darkmode version of the theme Nextcloud V25+ show a dark left menu where text is not well readable.

 Sceenshot on v2.35.1

![Screenshot 2024-03-11 000513](https://github.com/the-djmaze/snappymail/assets/5006150/8a608472-d9e1-44cc-b356-da3fac9d8baa)

Screenshot on version  v2.35.2

![Screenshot 2024-03-11 000909](https://github.com/the-djmaze/snappymail/assets/5006150/15bafe85-1ab7-4b6e-9572-7d21a54f757e)

**To Reproduce**
1. Activate the theme Nextcloud V25+ on a dark mode
2. The left navigation menu has the text not well readable.

**Comment by the-djmaze** [comment] 2024-03-11 09:23
Duplicate of #1463

**Closed by the-djmaze** 2024-03-11 09:23 UTC
Labels: bug, duplicate

**Comment by PeopleInside** [comment] 2024-03-11 10:21
The fix in the styles.css is never working for me

**Comment by PeopleInside** [comment] 2024-03-11 20:12
How can I fix this issue on my install?
