### ISSUE TITLE
[Squire] Editor behaves strangely

### ISSUE THREAD

**Issue by hampoelz** [the-djmaze/snappymail#1389] opened 2024-01-14 10:27 UTC
I had to write a lot of emails recently and noticed some strange behaviors in the editor:

- If I write in plain mode and then switch to HTML mode, an additional empty line is inserted after each line
- If I save a mail written in plain mode as a draft and then open it again, the writing mode changes to HTML
- Sometimes the undo (CTRL + Z) undoes a lot more than it should, but interestingly, the redo (CTRL + Y) allows me to go back to the stage I wanted with just one undo.
- The font size and family behaves very strangely with pasted text (or text with different formats)

As an example, I have copied together the following simple text. No font size is displayed in the first line. In the second line, the font size is 16px. In the third line, the font size is also 16px, although the text is significantly smaller than in the second line. It makes no difference whether I just click in the text or whether I select it.

![Screenshot from 2024-01-14 10-55-33](https://github.com/the-djmaze/snappymail/assets/28979769/0928bf67-26d3-4a68-ae55-62c21a5c20e1)
![Screenshot from 2024-01-14 11-03-42](https://github.com/the-djmaze/snappymail/assets/28979769/50debe80-e880-4c8a-abfe-23947364b650)
![Screenshot from 2024-01-14 10-55-53](https://github.com/the-djmaze/snappymail/assets/28979769/6d325913-5a84-4021-b0ff-3657771601cc)

The source code for this text looks like this:

```html
<div><span style="font-family: var(--font-face); font-size: var(--nc-default-font-size);">Test.</span><br></div><div><br></div><div><span style="font-family: var(--font-face); font-size: 13px;"><span style="font-size: 16px;">Test2.</span></span><br></div><div><br></div><div>Test3.<br></div><div><br></div>
```

Furthermore, if a text has different fonts / font sizes and I select the whole text, only the one that was selected first is shown in the selector. In this case, however, the selector should be empty so that you know that the whole text does not have the same font or font size.

**Environment:**
- Browser: Chrome 120
- SnappyMail Version: 2.32.0
- Mode: Nextcloud 28.0.1

I also experienced the same problems on the snappymail demo page.

**Comment by sm-boogie** [comment] 2024-01-24 17:08
I can confirm the insertion of extra new lines when opening a draft message for editing in plain text mode (set as default here).
Prior to opening it, the message looks fine (correct amount of new lines) in the SnappyMail preview. Also it doesn't matter whether I have previously edited said message with SnappyMail or any other client.

**Comment by codiflow** [comment] 2024-02-14 12:19
I can also confirm this strange behaviour but did not have time to look into this more in detail.

At least I noticed that for EVERY pasted text there is a new line inserted before and after the text – no matter if the copied text was HTML, plain text or whatever. I found my way to handle this but would really appreciate a fix here 😎

I recorded two video showing some of the strange behaviour:

https://github.com/the-djmaze/snappymail/assets/43847817/a56535c3-7835-4c67-8d26-ee2e32cd758c

https://github.com/the-djmaze/snappymail/assets/43847817/b66407df-2ccf-4f1f-80ed-56684f25c283

**Comment by phsc84** [comment] 2024-04-17 14:42
Quill 2.0 has been released!
https://slab.com/blog/announcing-quill-2-0/
https://github.com/quilljs/quill/releases/tag/v2.0.0

Are there any plans to replace Squire or at least offer Quill as an alternative? Would be happy to test! 😃

**Comment by phsc84** [comment] 2024-06-27 06:06
The behaviour of Squire is still a little bit annoying. Any chance we get Quill as an alternative?

**Comment by the-djmaze** [comment] 2024-07-15 12:45
> Any chance we get Quill as an alternative?

I will look into it

**Comment by koffienl** [comment] 2024-08-04 10:09
The recent behavior of https://github.com/the-djmaze/snappymail/issues/1666 is quite annoying, I see it is closed with a reference to this topic.

What is the current approach? Wait for the new editor or will there be a workaround to fix the linebreaks while waiting for the new editor?

**Comment by BiglifeMatt** [comment] 2024-08-09 16:24
Yes, waiting for the fix.  Is it being released soon or can we patch in the meantime?

**Comment by mohsensaeedi** [comment] 2024-09-29 21:49
We have this problem for 2.38.0 and earlier version. first line have many problem and wrong behavior for many actions such alignment, direction, font and font size and ...

Any idea to fix this bug?

**Comment by codiflow** [comment] 2024-10-02 20:53
Great to hear that 🔥

Just a quick note:
I noticed, that copy&pasting images directly into the editor does not work anymore since 2.38.0. Using the "Image button" in the menu bar still works and the image is pasted inline but the keyboard shortcut does not work anymore.

Maybe this has to do with the recent modifications?

**Comment by the-djmaze** [comment] 2024-10-02 20:59
> Maybe this has to do with the recent modifications?

It worked because i used a modified Squire.
Yet people started submitting original Squire2 in plugins because they used the latest Squire2 version and "should" be better.
So i threw away my modified Squire, forked Squire2 and now working in a branch to get most changes back, fix Squire2 issues and add improvements.
This way i could merge commits from the main project into my fork ;)

I will test the copy/paste, but maybe it is already solved in the [demo](https://snappymail.eu/demo/)

**Comment by codiflow** [comment] 2024-10-02 22:54
Just tested it in the demo – copy&paste is currently also not working there (I'm using Firefox).

Apart from that: Great work and thanks for the detailed explanation💪😎

**Comment by phsc84** [comment] 2024-10-15 19:59
Can this already be tested with Snappymail 2.38.2 or are there still changes coming?

**Comment by the-djmaze** [comment] 2024-10-15 20:03
You can already test with v2.38.2

**Comment by phsc84** [comment] 2024-10-17 20:54
I played around with 2.38.2. Looks much better now! Many thanks for the great work!
Just one small glitch I encountered so far: #1815 
Will continue testing...

**Comment by phsc84** [comment] 2024-11-17 15:02
Tested it now for quite a while. Looks all good so far. So I guess this issue could be closed, if you agree.

**Comment by the-djmaze** [comment] 2024-11-18 23:13
@phsc84 thanks for testing!

I will close this as no one else reports further issues.

**Closed by the-djmaze** 2024-11-18 23:13 UTC
Labels: bug
