### ISSUE TITLE
Question regarding CRLF/LF

### ISSUE THREAD

**Issue by FabulousGee** [the-djmaze/snappymail#43] opened 2020-11-27 23:11 UTC
Hey there,

found your fork while searching for a solution to my problem regarding bare LF's when sending emails from RainLoop.
I already tried your webmail, too, but got the same problem.

Whenever I send emails I get an error message stating that my email contains bare LF's (instead of CRLF line endings).
I already tried to locate your changes in the repo and found the following commit: https://github.com/the-djmaze/snappymail/commit/6e0d0b3b6e080651ba96241dff4fceb7647513b7?branch=6e0d0b3b6e080651ba96241dff4fceb7647513b7

But I can not identify which changes are influencing the LF/CRLF usage. Could you maybe point out, how I can chose LF/CRLF to be used? I am familiar with PHP, just not really into RainLoop/Snappymail.
Would appreciate any help. Thanks in advance and have a nice weekend!

**Comment by the-djmaze** [comment] 2020-11-29 19:04
The commit you reference is just the fix for inconsistensies in the source code.

The problem you have is something else.
The SMTP connection should convert LF to CRLF because CRLF is the standard in the SMTP RFC.
If not, this is a bug in RainLoop and SnapoyMail that must be resolved.

**Comment by FabulousGee** [comment] 2020-11-29 21:07
This is what I've logged when the error occurs. Maybe you can find any mistake in it or anything that triggers the error?
If I can help you with anything else, just let me know.

```
TAG1 CAPABILITY
TAG2 LOGIN "xxx" "xxx"
EHLO mail.xxx.de
AUTH LOGIN
ZmFiaWFuLmdpZXdhbGQ=
V2V3QXYsbXZmITIwMTc=
MAIL FROM:<xxx@xxx.de>
RCPT TO:<xxx@xxx.de>
DATA
MIME-Version: 1.0
Date: Sun, 29 Nov 2020 20:59:37 +0000
Content-Type: multipart/alternative;
 boundary="--=_RainLoop_225_506363235.1606683577"
From: "xxx - xxx"
 <xxx@xxx.de>
Message-ID: <xxx@xxx.de>
Subject: TESTemail
To: xxx@xxx.de
X-Originating-IP: xx.xx.xx.xx


----=_RainLoop_225_506363235.1606683577
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: quoted-printable

Das ist nur ein Test=0A=0Aein Test=0Amit verschiedenen Umbr=C3=BCchen=0A	=
Testtext 12345=0A123421345=0A12345=0A13245=0A32145=0Aasd=0Ag=0Aasdfg=0Asd=
ffg

----=_RainLoop_225_506363235.1606683577
Content-Type: text/html; charset="utf-8"
Content-Transfer-Encoding: quoted-printable

<!DOCTYPE html><html><head><meta http-equiv=3D"Content-Type" content=3D"t=
ext/html; charset=3Dutf-8" /></head><body><div data-html-editor-font-wrap=
per=3D"true" style=3D"font-family: arial, sans-serif; font-size: 13px;"><=
p>Das ist nur ein Test<br><br>ein Test<br>mit verschiedenen Umbr=C3=BCche=
n<br> </p><p>Testtext 12345<br>123421345<br>12345<br>13245<br>32145<br>as=
d<br>g<br>asdfg<br>sdffg<br> </p><signature></signature></div></body></ht=
ml>

----=_RainLoop_225_506363235.1606683577--
.
TAG3 LOGOUT

```

**Comment by the-djmaze** [comment] 2020-11-29 22:35
Pasting the log here kills the line endings.
I will have a look in the source if i can find it.

**Comment by FabulousGee** [comment] 2020-11-29 22:41
Thanks man. Though, I currently suspect the mailserver (hMailserver) since the logging did not appear to have any bare LF's in it.
This is why I just created a bug report on their project as well. You can find more detailed logs with screenshots (for line endings) right here: https://github.com/hmailserver/hmailserver/issues/357

You can close this issue meanwhile or leave it open until this is resolved - your choice.

**Comment by the-djmaze** [comment] 2020-11-29 22:57
I see another bug in your hMailserver log.
MySQL crashes and there's an email address leaked now.

Since you think hMail is at fault, i will close this issue.
As i know sometimes the issue is wrong conversion like LF -> CRLFLF or CRCRLF (especially with FTP text transfers instead of binary using Windows OS).
That's why i fixed the source to be POSIX.
It's a small hidden bug most Windows users don't understand/recognise.

**Closed by the-djmaze** 2020-11-29 22:57 UTC

**Comment by visualperception** [comment] 2020-11-29 23:02
Run hmailserver administrator, i.e. run hMailAdmin.exe from wherever you have it located.
then go to following: 
settings/protocols/smtp
then select from tabs on right: RFC Compliance.
Then tick: Allow incorrectly formatted line ending.
Then click save and then restart hMailserver and see how you go.
Can't guarantee it will work but it won't do any harm. I have mine ticked since there are so many old mail programs out there that don't comply with current RFC's, And a lot of badly formatted emails from the likes of PHP and Microsoft asp etc etc.

**Comment by FabulousGee** [comment] 2020-11-29 23:27
> Run hmailserver administrator, i.e. run hMailAdmin.exe from wherever you have it located.
> then go to following:
> settings/protocols/smtp
> then select from tabs on right: RFC Compliance.
> Then tick: Allow incorrectly formatted line ending.
> Then click save and then restart hMailserver and see how you go.
> Can't guarantee it will work but it won't do any harm. I have mine ticked since there are so many old mail programs out there that don't comply with current RFC's, And a lot of badly formatted emails from the likes of PHP and Microsoft asp etc etc.

Thanks for the hint, I know this. But I wanted it to be RFC compliant since we got some rejected mails from other mailservers so we need to keep it clean on our side...

> I see another bug in your hMailserver log.
> MySQL crashes (utf8mb4?) and there's an email address leaked now.
> 
> Since you think hMail is at fault, i will close this issue.
> As i know sometimes the issue is wrong conversion like LF -> CRLFLF or CRCRLF (especially with FTP text transfers instead of binary using Windows OS, and mac users in the past with OS9).
> That's why i fixed the source to be POSIX.
> It's a small hidden bug most Windows users don't understand/recognise.

Thanks for your hint, too, I saw that error and the corresponding mail. This is no leak, it's a public emailadress used for sending newsletters. Removed it, though... Just to be correct.

**Comment by the-djmaze** [comment] 2020-11-30 10:11
Although hMailserver is not year 2020 approved (last release 2017 and no DKIM, DMARC, port 587 and TLS 1.3 and x64 is still alpha).
I made a change to circumvent the hMailserver bug.

**Comment by visualperception** [comment] 2020-11-30 10:56
> Although hMailserver is not year 2020 approved (last release 2017 and no DKIM, DMARC, port 587 and TLS 1.3 and x64 is still alpha).
> I made a change to circumvent the hMailserver bug.

I know hMailServer-5.6.7-B2425 does support TLS1.3
