### ISSUE TITLE
Issue with themes 

### ISSUE THREAD

**Issue by Zero3K** [the-djmaze/snappymail#188] opened 2022-01-13 03:10 UTC
Sometimes a dark version of the theme (in this case, Squares) is chosen for me but its not selected as a theme. I notice it when reloading a tab from a crashed session of Google Chrome.

**Comment by the-djmaze** [comment] 2022-01-13 11:06
Why does Chrome crash?
This is not something SnappyMail can solve unless it is the source of the crash.

**Comment by Zero3K** [comment] 2022-01-13 13:35
It crashes/freezes because of memory issues. You can try to replicate this issue by using Task Manager to close the Chrome.exe processes (with SnappyMail being logged into an account), re-run Chrome, clicking on the SnappyMail tab, then signing back in (if necessary).

**Comment by the-djmaze** [comment] 2022-01-13 16:36
I don't have Windows OS.

An old PC i have that has SEGFAULTs due to broken ram modules never had the issue after crashes.
My new PC with 12th gen Intel can't crash, nor does my Mac.
So i have no idea how to replicate the issue.

**Comment by Zero3K** [comment] 2023-02-01 09:29
The admin of Openmbox.net has mentioned having this issue and how he temporarily fixes it:

"once I log into webmail from the stored session, the selected interface can't appear.
everytime I have to login out then re-login with username/password then got the correct interface."

**Comment by the-djmaze** [comment] 2023-02-01 10:11
When requesting `/` it returns an HTML document with the default theme/CSS.
The headers are:
```
expires: Mon, 26 Jul 1997 05:00:00 GMT
cache-control: no-store, no-cache, must-revalidate, max-age=0, post-check=0, pre-check=0
pragma: no-cache
```

Then at login it gets the `Theme` of the user (could be different).

So for now i made a small change so people can identify the issue.
In `<head>` the style element now has `data-name="..."`.
It will contain the current loaded theme name.

**Comment by Zero3K** [comment] 2023-02-01 14:30
He doesn't want to use the latest source code. He wants it as a release version.

**Comment by Zero3K** [comment] 2023-02-03 16:22
I think I know what is going on. Refreshing via F5 results in the Default theme being used instead of the selected one.

**Comment by the-djmaze** [comment] 2023-02-03 17:51
That should be solved in 2.25.3 due to cache issue

**Comment by Zero3K** [comment] 2023-02-05 03:32
I can confirm that the issue I made this report for has been fixed.

**Comment by Zero3K** [comment] 2023-02-09 14:20
Oh, it turns out that the refresh causing the theme to switch to the Default theme issue was fixed. But not the original issue. According to the data-name variable that you added to style, it is using the Default theme until I refresh the page. Then it uses the one I selected in the settings.

**Comment by the-djmaze** [comment] 2023-02-09 15:40
So it seems that Chrome is loading a cached version of the HTML that is invalid.

I have no idea yet how to force Chrome to reload automatically yet.

**Comment by Zero3K** [comment] 2023-02-09 15:48
https://stackoverflow.com/questions/26111389/chrome-keeps-loading-a-old-cache-of-my-website

**Comment by the-djmaze** [comment] 2023-02-09 15:57
Ehm... the headers are:
```
cache-control: no-store, no-cache, must-revalidate, max-age=0, post-check=0, pre-check=0
expires: Mon, 26 Jul 1997 05:00:00 GMT
pragma: no-cache
```

**Comment by Zero3K** [comment] 2023-02-09 16:01
https://serverfault.com/questions/1030105/my-browser-keeps-showing-cached-page-despite-sending-no-cache-no-store-must-re

**Comment by the-djmaze** [comment] 2023-02-09 21:22
I will change the header and we will see if it works

**Comment by Zero3K** [comment] 2023-02-09 22:40
Please make a new version of it and I will let him know about it.

**Comment by Zero3K** [comment] 2023-02-11 01:49
It has been fixed thanks to that change.

**Comment by Zero3K** [comment] 2023-02-12 15:01
I stand corrected. It is still not fixed.

**Comment by Zero3K** [comment] 2023-02-13 16:10
How about adding code that checks if the user selected theme isn't being used and then to change to it if so?

**Comment by Zero3K** [comment] 2023-02-14 14:51
Would that work?

**Comment by the-djmaze** [comment] 2023-02-14 14:52
The code already does when it fetches theme within AppData request.
No AppData request, no luck fixing it.

**Comment by Zero3K** [comment] 2023-02-14 14:55
Is there any way I can debug it further?

**Comment by the-djmaze** [comment] 2023-02-14 14:59
Clear cache of Edge and try again.

**Comment by Zero3K** [comment] 2023-02-14 15:04
I closed all Microsoft Edge windows, ended all msedge.exe instances, deleted the Cache folder, ran Microsoft Edge, restored all of the closed windows, and the clicked on the tab containing SnappyMail. The issue showed up.

**Comment by the-djmaze** [comment] 2023-02-14 16:11
> restored all of the closed windows

That is the issue! Don't restore as that loads the old cached data.
1. close all windows properly
2. Settings -> Privacy -> Clear browsing data 
![afbeelding](https://user-images.githubusercontent.com/3752035/218793790-3381bd21-8fc9-47e7-b045-2c839690d7cd.png)

**Comment by Zero3K** [comment] 2023-02-14 16:15
I am not restoring the cache, I am re-opening the tabs in the closed windows.

**Comment by the-djmaze** [comment] 2023-02-14 18:48
I have no idea how, nor how Edge works, nor if you have some caching server inbetween.
Cloudflare or other can be the problem.

**Comment by Zero3K** [comment] 2023-02-14 18:55
1. I do not have a caching server.
2. How do I determine that?

**Comment by Zero3K** [comment] 2023-02-14 18:58
Maybe this will help:

https://stackoverflow.com/a/42149723/8067355

**Comment by the-djmaze** [comment] 2023-02-14 19:45
The issue is simple.
When loading the initial index.html it contains the default theme.
Then a small part of AppData is fetched to initiate login.
After login the new AppData is loaded and contains user theme.

When already logged in, the first AppData contains all required data.

So, to find out why your browser is failing:
1. Open developer tools
2. Look at the network tab
3. Open SnappyMail
4. Analyze the AppData requests in the network tab if it contains theme data

**Comment by Zero3K** [comment] 2023-02-14 19:52
How do I know if it contains theme data?

**Comment by Zero3K** [comment] 2023-02-14 20:13
How about having be with a ?ver=100 or so after it?

**Comment by the-djmaze** [comment] 2023-02-14 22:39
> How about having be with a ?ver=100 or so after it?

Is already

**Comment by Zero3K** [comment] 2023-02-14 22:45
Well, I just tried to replicate it by following the same steps after he upgraded to the latest version. It didn't happen. So, it was most likely fixed by https://github.com/the-djmaze/snappymail/commit/0c6950d49c60819c164ca418ee9b1d750edffa10 and/or https://github.com/the-djmaze/snappymail/commit/8b02d7f892980160428d4d884578fe26fb02ad27.

**Comment by Zero3K** [comment] 2023-02-18 16:14
Any thoughts on this?

**Comment by Zero3K** [comment] 2023-02-19 14:20
The SnappyMail content isn't being cached according to the Application tab of Developer Tools.

**Comment by Zero3K** [comment] 2023-02-19 20:14
Weird. It looks like it is ignoring the AppData settings until I refresh it. The theme is being set properly according a screenshot of the data of the AppData URL that was captured by Fiddler. Here's the screenshot:

![image](https://user-images.githubusercontent.com/6194332/219972874-c16bb704-f690-4390-bf55-a3a9f77aaf56.png)

**Comment by the-djmaze** [comment] 2023-02-21 11:32
No, but i made changes for next release to get that info better.

**Comment by Zero3K** [comment] 2023-02-21 13:17
What kind of changes?

**Comment by the-djmaze** [comment] 2023-02-21 18:53
AppData is now returned as JSON.
The response is now properly readable instead of a very long rl.init string.

**Comment by Zero3K** [comment] 2023-02-21 20:16
Okay. I can now say that it has been fixed.

**Comment by the-djmaze** [comment] 2023-02-22 14:13
Good 👍

**Comment by Zero3K** [comment] 2023-02-23 15:02
Ugh, it is still happening.

**Comment by the-djmaze** [comment] 2023-02-23 15:03
Fixed, not fixed, fixed, not fixed, , fixed, not fixed. Chrome should make up his mind :tongue:

**Comment by Zero3K** [comment] 2023-02-23 15:24
![image](https://user-images.githubusercontent.com/6194332/220950208-dcab4294-fdda-4cd1-a8e6-c50dfa29b560.png)
![image](https://user-images.githubusercontent.com/6194332/220950523-ba4b6cb7-17c8-4b97-a6aa-39c7784a4880.png)

I wonder if it is possible to have the AppData URL loaded before the Index page. So that way the Index page always uses the settings provided by the AppData URL.

**Comment by the-djmaze** [comment] 2023-02-23 15:45
> I wonder if it is possible to have the AppData URL loaded before the Index page. 

Not possible as HTML needs to load script.

> So that way the Index page always uses the settings provided by the AppData URL.

According to the AppData your theme is `Squares`.
The index should also load `Squares` but shows `Default`
The index receives the value from GetTheme() in https://github.com/the-djmaze/snappymail/blob/master/snappymail/v/0.0.0/app/libraries/RainLoop/Actions/Themes.php

So something is going wrong on the server, and i'm not the owner of that server

**Comment by Zero3K** [comment] 2023-02-23 15:52
It's not a problem with how it is getting the Themes setting from AppData?

**Comment by Zero3K** [comment] 2023-02-23 16:30
I was able to replicate it with the demo on snappymail.eu.

**Comment by Zero3K** [comment] 2023-02-24 13:39
Are you also able to do so on it?

**Comment by Zero3K** [comment] 2023-02-24 17:43
You should re-open this ticket.

**Comment by the-djmaze** [comment] 2023-02-25 18:27
Not really. I did notice on some dutch forum several people have issues with Chrome and cache in many different websites.

So probably it is a Chrome bug.

**Comment by Zero3K** [comment] 2023-02-25 18:34
I don't see a ?v=number at the end of the URL.

**Comment by the-djmaze** [comment] 2023-02-26 07:22
Since this bug in Chrome is reported for many years and still happening on many websites, i will close this as unresolvable.
There's nothing we can do.

**Closed by the-djmaze** 2023-02-26 07:22 UTC

**Comment by Zero3K** [comment] 2023-02-26 07:50
Not even try the thing that I mentioned?

**Comment by Zero3K** [comment] 2023-02-27 00:17
Firefox also has the issue according to the owner of the email service.

**Comment by Zero3K** [comment] 2023-03-01 14:08
They are aggressively caching CSS.

**Comment by Zero3K** [comment] 2023-03-02 00:53
I guess you won't try the change.

**Comment by the-djmaze** [comment] 2023-03-03 10:02
SnappyMail uses:
/ = `cache-control: no-store`
/?/AppData/0/[random]/ = `cache-control: no-store`

If a browser decides to not behave as we want, we can't fix that.

**Comment by the-djmaze** [comment] 2023-03-04 22:51
The code is already random and like v=1

**Comment by Zero3K** [comment] 2023-03-05 00:00
So, the URL does change when a user changes a setting?

**Comment by Zero3K** [comment] 2023-03-09 15:29
How about using a cookie value instead of JSON?

**Comment by Zero3K** [comment] 2023-03-11 08:41
I guess you're not interested in adding it to the demo so I can see if it fixes the issue or not.

**Comment by Zero3K** [comment] 2023-03-13 14:52
Using a cookie for the Theme won't work?
