### ISSUE TITLE
Answering or forwarding a mail is not possible

### ISSUE THREAD

**Issue by designor** [the-djmaze/snappymail#1033] opened 2023-03-21 12:51 UTC
**Describe the bug**
If i want to answer a mail, or answer all or forward.. always the standard dialog for a new mail pops up without any content of the "answered" mail.
No recipient, No attachments, nothing
Version 2.27.0

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please complete the following information:**
- Browser: [e.g. chromium 100, firefox 100, safari 14, mobile]
- IMAP daemon: [e.g. courier, dovecot]
- PHP version:
- SnappyMail Version:

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
Place them here (few lines) or as attachments (many lines)

**Additional context**

**Comment by the-djmaze** [comment] 2023-03-21 12:59
Duplicate of #1027

**Closed by the-djmaze** 2023-03-21 12:59 UTC
Labels: bug, duplicate
