### ISSUE TITLE
Nextcloud Hub 8 (29.0.4) AIO falls into maintenance mode after updating to SnappyMail Version 2.37.2

### ISSUE THREAD

**Issue by pagenstedt** [the-djmaze/snappymail#1727] opened 2024-08-28 09:55 UTC
**Describe the bug**
Nextcloud Hub 8 (29.0.4) AIO falls into maintanance mode after updating to SnappyMail Version 2.37.2

**To Reproduce**
1. Update/Install Snappymail from Nexcloud App Menu
2. Reload Nextcloud web frontend
3. See message: this site is in maintanance mode

**Expected behavior**
App should be updated, Nextcloud should work with updated app

**Comment by the-djmaze** [comment] 2024-08-28 20:52
Duplicate of #929

See https://github.com/the-djmaze/snappymail/issues/929#issuecomment-1818911724

**Closed by the-djmaze** 2024-08-28 20:52 UTC
