### ISSUE TITLE
Snappymail does not show empty lines in mail body

### ISSUE THREAD

**Issue by lje** [the-djmaze/snappymail#1696] opened 2024-08-08 10:54 UTC
**Describe the bug**
Snappymail does not show empty lines in mail bodys.

This is what I type:
![Screenshot 2024-08-08 124403](https://github.com/user-attachments/assets/b929ba42-296b-4cbc-b980-560902ff5350)

This is what I see in Sent and Inbox (I sent the mail to myself):
![Screenshot 2024-08-08 124534](https://github.com/user-attachments/assets/1951f0f3-b470-447c-a72b-67b84e107e80)

This is the raw message body:
```
--cdac2475-53e2-4401-85c4-e6f831de358a-1
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: quoted-printable

Line 1

Line=202
--cdac2475-53e2-4401-85c4-e6f831de358a-1
Content-Type: text/html; charset="utf-8"
Content-Transfer-Encoding: quoted-printable

<!DOCTYPE html><html><head><meta http-equiv=3D"Content-Type" content=3D"t=
ext/html; charset=3Dutf-8"></head><body><div>Line 1</div><div></div><div>=
Line 2</div><div></div></body></html>
--cdac2475-53e2-4401-85c4-e6f831de358a-1--
```

The empty line between "Line 1" and "Line 2" is clearly visible in the plain text version of the message. But the HTML version seems to miss a ```<br>``` or something like that. A ```<div></div>``` apparently will not create an empty line.

**Please complete the following information:**
- Browser: Firefox 128.0.3
- IMAP daemon: dovecot
- PHP version: 8.1.29
- SnappyMail Version: 2.36.4
- Mode: standalone

**Comment by the-djmaze** [comment] 2024-08-08 11:08
Duplicate of #1672

**Closed by the-djmaze** 2024-08-08 11:08 UTC
Labels: duplicate
