### ISSUE TITLE
Spacing does not maintain on the reciepeints end

### ISSUE THREAD

**Issue by BiglifeMatt** [the-djmaze/snappymail#1672] opened 2024-07-18 15:28 UTC
**Describe the bug**
Multiple users are noticing that when they submit an email with formatted spaces between rows, those double spaces seem to get dropped and the message is all compressed line by line for the recipient.  

**To Reproduce**
1. Create a new email
2. As you type in the body include several blank rows via hard returns
3. Send the message
4. Recipient will get the message but any empty lines seemed to be removed from the original format intended by the sender.

**Expected behavior**
The email received should have the same formatting as the sender created.

**Screenshots**
Here is the layout in SnappyMail
![image1](https://github.com/user-attachments/assets/3d263807-c3f3-4540-9d32-ac64fd2ca752)

Here is the way the recipient sees the spacing
![image](https://github.com/user-attachments/assets/712f9cad-39c7-4624-93eb-cfc625fa2f85)

**Please complete the following information:**
- Browser: various browsers and email clients
- IMAP daemon: dovecot
- PHP version: 8.1.2
- SnappyMail Version: 2.36.4
- Mode: nextcloud

**Comment by the-djmaze** [comment] 2024-07-22 14:01
Duplicate of #1666

**Closed by the-djmaze** 2024-07-22 14:01 UTC

**Comment by lje** [comment] 2024-08-10 11:38
Ok, thanks. I've reverted to 2.36.3 (which doesn not have this bug) until a fix is available.

**Comment by BiglifeMatt** [comment] 2024-08-10 11:54
> Ok, thanks. I've reverted to 2.36.3 (which doesn not have this bug) until a fix is available.

How do you revert an app?
