### ISSUE TITLE
Display the number of unread mails in mailbox in tab title

### ISSUE THREAD

**Issue by schmitz-ens** [the-djmaze/snappymail#1682] opened 2024-07-23 13:24 UTC
Hello,
and thanks for this great webmail.

Some of my users would like the number of unread email displayed in the title of the tab (at the begninning of the title).

Roundcube does that, and it saves them from having to actually open the tab to check if a new email arrived.

Something like this (in this screenshot I have one unread email) : 

![image](https://github.com/user-attachments/assets/4b1577d8-7b95-4736-bdcd-9026c21d3b55)

Would it be possible ?

Thx.

**Comment by the-djmaze** [comment] 2024-08-06 09:43
Duplicate of #380

**Closed** 2024-08-06 11:41 UTC
Labels: duplicate
