### ISSUE TITLE
Edit and delete the Tags

### ISSUE THREAD

**Issue by warumwirleben** [the-djmaze/snappymail#1658] opened 2024-07-09 13:35 UTC
In the actual version:
I am missing a way to edit or remove the tags.

Is this function planed?

Thanks in advance!

**Comment by the-djmaze** [comment] 2024-07-09 22:40
Duplicate of #1536

**Closed** 2024-07-09 22:41 UTC
Labels: duplicate

**Comment by warumwirleben** [comment] 2024-07-10 16:29
Sorry, I had searched but didn't find the original.
