### ISSUE TITLE
account switch not working 

### ISSUE THREAD

**Issue by HenkVirtual** [the-djmaze/snappymail#805] opened 2022-12-28 07:49 UTC
After update to snappymail version 2.24.2 it is not possible to switch to your other mail account, you can use the pulldown menu, but snappymail keeps switching to the default account.
running nextcloud 25.0.2 php 8.0 
when reverting back to version 2.24.1 account switch is working again.

**Comment by the-djmaze** [comment] 2022-12-28 08:45
Duplicate of #802

**Closed by the-djmaze** 2022-12-28 08:45 UTC
Labels: duplicate
