### ISSUE TITLE
After upgrade to Nextcloud 29.0.1 snappymail is not accessible thought top icon menu bar

### ISSUE THREAD

**Issue by FelixDefrance** [the-djmaze/snappymail#1596] opened 2024-05-24 21:10 UTC
**Describe the bug**

After upgrade nextcloud to 29.0.1 the link to snappymail (https://URL/apps/snappymail/) point to a wrong app. 
Icon is present in the top menu bar, but redirect to *https://URL/apps/dashboard/*.

**workaround** 
To access to snappymail, add */apps/snappymail/* instead of */apps/dashboard/* in your browser URL address

**Note**
1. When we are on snappymail apps, icon link point in the richet uri (/apps/snappymail/)
2. When I desactivate snappymail apps from NC admin panel, it  was impossible to readd the app and you need to enable the apps by CLI (occ app:enable snappymail)

**Comment by the-djmaze** [comment] 2024-05-26 11:31
Duplicate of #1577

**Closed by the-djmaze** 2024-05-26 11:31 UTC
