### ISSUE TITLE
Nextcloud: error before update to last version

### ISSUE THREAD

**Issue by sergiovl** [the-djmaze/snappymail#1704] opened 2024-08-12 20:50 UTC
After update Nextcloud to version 29.0.4 and Snappymail app to version 2.37.1, show this message in Nextcloud window: 

```
An error occurred.
Please refresh the page and try again.SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

```

I looking for Nextcloud log:

`{"reqId":"5MwA7jydxfZzvW2T2ejp","level":3,"time":"August 12, 2024 20:42:17","remoteAddr":"192.168.X.Y","user":"administrador","app":"PHP","method":"GET","url":"/apps/snappymail/","message":"json_decode(): Passing null to parameter #1 ($json) of type string is deprecated at /var/www/html/apps/richdocuments/lib/Service/CapabilitiesService.php#149","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:129.0) Gecko/20100101 Firefox/129.0","version":"29.0.4.1","data":{"app":"PHP"}}`

I try to reinstall app but no effect.

**Comment by plinss** [comment] 2024-08-12 21:22
Same issue with 2.37.0 and Nextcloud 29.0.4. Reverting to 2.36.4 seems to fix it.

**Comment by the-djmaze** [comment] 2024-08-12 22:04
Duplicate of #1703

**Comment by the-djmaze** [comment] 2024-08-12 22:06
> "url":"/apps/snappymail/"
> "message":"json_decode(): Passing null to parameter #1 ($json) of type string is deprecated at /var/www/html/apps/richdocuments/lib/Service/

So what is this `richdocuments` app, and why does it kill SnappyMail?

**Comment by the-djmaze** [comment] 2024-08-12 22:10
Also see #1663 and #1535

**Closed** 2024-08-12 22:29 UTC
Labels: duplicate, external, Nextcloud
