### ISSUE TITLE
2.19.6 can not see Mail in my Mailbox

### ISSUE THREAD

**Issue by sgutermann** [the-djmaze/snappymail#609] opened 2022-11-01 22:14 UTC
**Describe the bug**
Fresh install Debian 11 and fresh v25 nextcloud. Fresh install SnappyMail 2.19.6. Added Domain Details in the backend. Logged into Snappy.

It does not "keep" my credentials.
It shows my Mailbox and my custom IMAP Folders, but NO Mails.

**To Reproduce**
Setup fresh and try.

**Expected behavior**
See my Mail and keep my credentials.

**Comment by sgutermann** [comment] 2022-11-01 22:15
Did the identical with the old rainloop and it worked out of the box.

**Comment by the-djmaze** [comment] 2022-11-01 22:35
Duplicate of #604

**Closed by the-djmaze** 2022-11-01 22:35 UTC
