### ISSUE TITLE
Save as .eml in nextcloud

### ISSUE THREAD

**Issue by Pasquet62** [the-djmaze/snappymail#1425] opened 2024-02-08 15:18 UTC
When I select multiple emails and go to export them to .eml if there are emails with an identity subject, it doesn't create a new file, but overwrites the data. Result does not save all emails correctly
![image](https://github.com/the-djmaze/snappymail/assets/8092369/7bde4e3f-abd4-4cb4-a1c0-98e146957a5e)
![snappy](https://github.com/the-djmaze/snappymail/assets/8092369/973c421d-ab71-49a5-878a-761ed5de02ba)

**Comment by the-djmaze** [comment] 2024-02-08 16:18
Duplicate of #1381 and solution is released in v2.33

**Comment by Pasquet62** [comment] 2024-02-08 16:24
![image](https://github.com/the-djmaze/snappymail/assets/8092369/0014d8fb-2b2f-42a1-9c69-1af42044157d)

**Comment by the-djmaze** [comment] 2024-02-08 17:02
SnappyMail Admin -> Extensions -> Nextcloud version says: ....

**Comment by the-djmaze** [comment] 2024-02-08 17:07
No: SnappyMail Admin -> Extensions -> Nextcloud version says v2.29 ?

**Comment by Pasquet62** [comment] 2024-02-08 17:08
![image](https://github.com/the-djmaze/snappymail/assets/8092369/62267147-a173-4f8a-a971-666021f344ba)

**Comment by Pasquet62** [comment] 2024-02-14 15:42
updated to 2.34.1 but now it doesn't save anything

**Comment by Pasquet62** [comment] 2024-02-14 15:43
![image](https://github.com/the-djmaze/snappymail/assets/8092369/f36d30c3-dcc9-4e08-8d85-f4215d1cd3b1)

**Closed** 2024-02-18 15:44 UTC
Labels: bug, Nextcloud
