### ISSUE TITLE
Failed loading javascript file

### ISSUE THREAD

**Issue by christianwohlgemuth** [the-djmaze/snappymail#1802] opened 2024-10-13 15:52 UTC
**Describe the bug**
the file /apps/snappymail/app/snappymail/v/2.38.2/static/js/min/libs.min.js cannot be loaded.
the error occurs since the update from Nextcloud to version 29.0.7

**To Reproduce**
1. open nextcloud
2. Click on the mailbutton

**Screenshots**
![Clipboard_10-13-2024_01](https://github.com/user-attachments/assets/9770a921-538e-42bd-9ef2-025b3c43b573)

**Please complete the following information:**
- Firefox 131.02
- SnappyMail Version: 2.38.2
- Mode: nextcloud app (NC runs inside Docker)

**Comment by the-djmaze** [comment] 2024-10-13 16:15
Try that url manually.
It must be a problem on your server.

**Comment by the-djmaze** [comment] 2024-10-13 16:17
duplicate of #1535

**Comment by christianwohlgemuth** [comment] 2024-10-13 16:32
Hello @the-djmaze,

also manually the file don't exists
# curl -I https://nextcloud.local/apps/snappymail/app/snappymail/v/2.38.2/static/js/min/libs.min.js
HTTP/2 404

I have seen that the apps are available under custom_apps
# curl -I https://nextcloud.local/custom_apps/snappymail/app/snappymail/v/2.38.2/static/js/min/libs.min.js
HTTP/2 200

I think it's a problem with the custom_apps folder

**Comment by the-djmaze** [comment] 2024-10-13 19:27
> I have seen that the apps are available under custom_apps

That's why i linked to that issue.
Do what is mentioned there:
https://github.com/the-djmaze/snappymail/issues/1703#issuecomment-2284698465

**Closed by the-djmaze** 2024-10-13 19:27 UTC
Labels: duplicate, Nextcloud
