### ISSUE TITLE
Nextcloud error before entering Login Screen

### ISSUE THREAD

**Issue by alabre** [the-djmaze/snappymail#605] opened 2022-11-01 07:43 UTC
SnappyMail: Version 2.19.6
Browser: Firefox 106
Server: Nextcloud 24.0.6 on Apache
Note: All was fine until updating to 2.19.6

What happens:

When I click on the SnappyMail icon in my App bar in nextcloud I get a nextcloud error page and find in the logs:
[index] Fehler: Exception: Undefined constant "OCA\SnappyMail\Util\RAINLOOP_APP_LIBRARIES_PATH" in file '.../nextcloud/apps/snappymail/lib/Util/SnappyMailHelper.php' line 16 at <<closure>>

0. .../nextcloud/lib/private/AppFramework/App.php line 172
   OC\AppFramework\Http\Dispatcher->dispatch()
1. .../nextcloud/lib/private/Route/Router.php line 298
   OC\AppFramework\App::main()
2. .../nextcloud/lib/base.php line 1030
   OC\Route\Router->match()
3. .../nextcloud/index.php line 36
   OC::handleRequest()

And instead of this I would expect that the SnappyMail login screen appears and I can log on.

How to reproduce: Click on the SnappyMail icon in the App-Bar in Nextcloud

Thanks for SnappyMail! :-)

Update: Removed root links

**Comment by the-djmaze** [comment] 2022-11-01 09:09
Duplicate of #601

**Closed by the-djmaze** 2022-11-01 09:09 UTC
