### ISSUE TITLE
Nextcloud enters maintenance mode after updating snappymail

### ISSUE THREAD

**Issue by elhananjair** [the-djmaze/snappymail#909] opened 2023-02-04 15:27 UTC
**Describe the bug**
Hello @the-djmaze 
starting from last 3 snappymail updates nextcloud enters maintenance mode after updating snappymail. changing maintenance mode to off is not fixing the issue, but I had to disable snappymail using `OCC` from the terminal and set maintenance mode to off and then restart `php-fpm`. After that, I log in to nextcloud and enable it from the administration setting. 

**To Reproduce**
1. Go to nextcloud app setting
2. Click on snappymail app and update it 
3. After the update ended nextcloud goes into maintenance mode

**Expected behavior**
After an update nextcloud should be active 

**Screenshots**

**Please complete the following information:**
- Browser: Firefox 109
- IMAP daemon: [e.g. courier, dovecot]
- PHP version: 8.0.26
- SnappyMail Version:  2.25.3

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
Place them here (few lines) or as attachments (many lines)

**Additional context**

**Comment by the-djmaze** [comment] 2023-02-04 15:45
Duplicate of #904

**Closed** 2023-02-04 15:47 UTC
Labels: duplicate, external
