### ISSUE TITLE
"Authentication failed" to admin panel after new installation on Nextcloud

### ISSUE THREAD

**Issue by rcsilva83** [the-djmaze/snappymail#607] opened 2022-11-01 19:35 UTC
**Describe the bug**
After installing the Nextcloud app, I try to login to admin panel with the default credentials and I get "Authentication failed".

**To Reproduce**
1. Install SnappyMail app on Nextcloud
2. Go to to "Additionnal settings" on Nextcloud
3. Click on the "Go to SnappyMail Webmail admin panel" link
4. Try to login with the provided admin credentials
5. Get message "Authentication failed"

**Expected behavior**
Enter on SnappyMail admin panel

**Please complete the following information:**
- Browser: Firefox 106.0.3 
- IMAP daemon: I don't know
- PHP version: 7.4.3
- SnappyMail Version: 2.19.6
- Nextcloud version: 24.0.4

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
[snappymail.log](https://github.com/the-djmaze/snappymail/files/9913468/snappymail.log)

**Comment by the-djmaze** [comment] 2022-11-01 20:57
Duplicate of #602

**Closed** 2022-11-01 20:58 UTC
Labels: bug, duplicate
