### ISSUE TITLE
Shortcut [SHIFT] + [B] prevents uppercase B from being entered into search field

### ISSUE THREAD

**Issue by codiflow** [the-djmaze/snappymail#1794] opened 2024-10-03 17:37 UTC
**Describe the bug**
If you want to enter uppercase B into any search field, nothing appears. I think the recently added keyboard shortcut [SHIFT] + [B] (https://github.com/the-djmaze/snappymail/issues/1690) prevents this and tries to "switch background color" of the current message (no matter if a message is opened or not).

**To Reproduce**
1. Click into any of the search fields
2. Try to enter uppercase B using [SHIFT] + [B]
3. See that no uppercase B appears but the background color of the message (if any is opened) switches

**Expected behavior**
It should write uppercase B instead of switching the background color of the selected message (if any). Maybe the shortcut should be changed or the background color switching should be disabled if a search fields is in focus.

**Please complete the following information:**
- Browser: Firefox 130.0
- SnappyMail Version: 2.38.0
- Mode: docker

**Comment by the-djmaze** [comment] 2024-10-03 21:58
Duplicate of #1780

**Closed by the-djmaze** 2024-10-03 21:58 UTC
Labels: duplicate
